name: Build Binaries

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ 1.23 ]
        os: [ linux, darwin ]
        arch: [ amd64, arm64 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build binaries
      run: |
        mkdir -p build
        GOARCH=${{ matrix.arch }} GOOS=${{ matrix.os }} go build -ldflags "-s -w" -trimpath -o build/${{ matrix.os }}-${{ matrix.arch }}/tenderduty main.go

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: tenderduty-${{ matrix.os }}-${{ matrix.arch }}
        path: build/${{ matrix.os }}-${{ matrix.arch }}/
